### ISSUE TITLE
Triangle Space Theme background not working with new Discord update

### ISSUE THREAD

**Issue by DanRocsMinecraft** [xNightWulf/ThemesForBetterDiscord#3]
I recently updated Discord to the latest version and the Triangle Space Theme with the no member hover doesnt load the triangle background correctly... The hover version works, but I wanted to use the nonhover one as you can't scroll through the memberlist using the hover version... Thank you!

**Comment by xNightWulf** [comment]
Triangular_Space has been updated so that scrolling on the memberlist now works again. Thanks for letting me know. Triangular_Space without hover member list has been updated to have a background again.

**Comment by DanRocsMinecraft** [comment]
Thank you! Much appreciated

**Comment by xNightWulf** [comment]
Changes may take a bit before rawgit updates. But the changes are there
